### PR TITLE
Add dedicated Workers and Webhooks Instances

### PR DESCRIPTION
**Pull request by swarnat**
I currently play a little bit to integrate the scaling options of n8n into this helm chart.

I would be happy about users, who have the chance to test. Because my lack of experience with n8n maybe oversee something. But in my eyes a deployment to k8s don't make sense without decentralized workers/incoming webhooks and a little bit HA options

Other topics of this merge:

- Updated n8n version to latest one. (**Important: I got an error in n8n migration, when I update existing environment, so pay attention to this and backup database before update**)
- Modify Ingress for K8s 1.22+
- Add podLabels to Deployment to allow definition of Network Policies

**ToDo before Merge:**

- [x] Cleanup Deployments and define helpers for general options
- [x] Update Redis Chart to latest version
- [x] Extend README

Any Feedback is welcome

### CODE REVIEW

**Comment by vaelant** [comment]
Tested this before the branch conflicts and it worked flawlessly, thanks for the work. Having a solid  kubernetes HA nocode tool will make many people happy. 

To save some time, here's a minimum set of values necessary for notes in case users want to test themselves.

Note: You'll need a postgreSQL instance setup ahead of time to connect:

```
n8n:
  encryption_key: <generate and replace with encryption string>

config:
  database:
    type: postgresdb
    postgresdb:
      database: n8n
      host: <postgresdb url>
      port: 5432
      user: <postgresdb user>

secret:
  database:
    postgresdb:
      password: <postgresdb password>


ingress:
  enabled: true
  hosts:
    - host: your.n8n.hostname
      paths:
       - /
  tls:
    - secretName: n8n-tls
      hosts:
        - your.n8n.hostname

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80


scaling:
  enabled: true
  
  worker:
    count: 2
    concurrency: 2

  webhook:
    enabled: true
    count: 1

  redis:
    host: <redis host headless>
    password: <redis password>

redis:
  enabled: true
  global:
    redis:
      password: <redis password>
  architecture: standalone

  master:
    persistence:
      enabled: false
      existingClaim: ""
      size: 2Gi  
```

Thanks for tuning the chart, looking forward to merge.

**Comment by Vad1mo** [comment]
Happy to hear, @swarnat can you resolve the issues and I'll merge your changes!

**Comment by swarnat** [comment]
Of course. I will solve it within next day

**Comment by swarnat** [comment]
Conflict is solved and directly updated to latest version
Update is quickly tested in our environment.
We are using this "HA" setup since october and do not get any issues.

**Pull request merged**
